joint_names: [right_arm_1_joint, right_arm_2_joint, right_arm_3_joint, right_arm_4_joint, right_arm_5_joint, right_arm_6_joint, right_arm_7_joint]

#variance in [rad]
pos_meas_noise_var: 0.0000001 #0.001
process_noise_var: [100.0, 100.0, 100.0] #[0.0, 0.0, 10.0]
prior_var: [0.0001, 0.5, 0.5] #[0.0001, 0.5, 0.5]

loop_frequency: 130

delta_t: 0.00769